# Generated by Django 3.1.5 on 2021-01-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(db_column='sitName', max_length=45, unique=True),
        ),
    ]
