# Generated by Django 3.1.5 on 2021-01-19 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20210118_2312'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('name', 'parent')},
        ),
    ]
